"""Meridian — the public reference org (the benchmark dataset, not a teaching toy).

Designed per the public-org spec: 10 accounts, ~47 claims, 22 probes with >=5 per
conflict type, both resolution rules (recency AND binding authority, where recency
actively misleads), anti-prior values throughout (nothing answerable from genre
defaults), and CRM records wide enough that per-field provenance (det-4) measures
something real. Every expected_answer is in the exact wording the org materializes.
"""

from __future__ import annotations

from tessera.models import (
    Blueprint,
    Claim,
    ConflictType,
    ExpectedBehavior,
    Probe,
    ResolutionRule,
)


def _field(claim_id: str, subject: str, predicate: str, value, *,
           asserted_at: str | None = None, authority: int | None = None) -> Claim:
    return Claim(claim_id=claim_id, subject=subject, predicate=predicate, value=value,
                 silo="crm", asserted_at=asserted_at, authority=authority,
                 render={"as": "field"})


def _prose(claim_id: str, subject: str, predicate: str, value, template: str, *,
           asserted_at: str | None = None, authority: int | None = None) -> Claim:
    return Claim(claim_id=claim_id, subject=subject, predicate=predicate, value=value,
                 silo="docs", asserted_at=asserted_at, authority=authority,
                 render={"as": "prose", "template": template})


def build_meridian_blueprint() -> Blueprint:
    claims = [
        # ---- none: cross-silo chains (CRM holds the key, Docs hold the rule) ----
        _field("veltrix.plan.crm", "Veltrix Labs", "support_plan", "Prime-7"),
        _prose("plan.prime7.docs", "Prime-7 plan", "response_window", "7 hours",
               "Prime-7 plan tickets get a first response within {value}."),
        _field("bluepine.manager.crm", "Bluepine Logistics", "account_manager",
               "Dana Okafor"),
        _prose("bluepine.countersign.docs", "Bluepine Logistics", "renewal_countersigner",
               "the account manager",
               "Bluepine renewal orders are countersigned by {value}."),
        _field("halcyon.terms.crm", "Halcyon Foods", "payment_terms", "net-45"),
        _prose("terms.net45.docs", "net-45 terms", "late_surcharge", "1.8%",
               "Accounts on net-45 terms accrue a {value} monthly surcharge on late invoices."),
        _field("kovacs.region.crm", "Kovacs Industrial", "warehouse_region",
               "Region 4-East"),
        _prose("region.4east.docs", "Region 4-East", "dispatch_hub", "Brno",
               "Region 4-East dispatches ship from the {value} hub."),
        _field("northgate.contractform.crm", "Northgate Medical", "contract_form",
               "MSA-2024rev"),
        _prose("msa2024.cap.docs", "MSA-2024rev", "liability_cap", "$425k",
               "Under MSA-2024rev the liability cap is {value} per incident."),
        _field("arcadia.plan.crm", "Arcadia Systems", "support_plan", "Juniper"),
        _prose("plan.juniper.docs", "Juniper plan", "triage_window", "90 minutes",
               "Juniper-plan tickets are triaged within {value}."),

        # ---- resolvable, recency_wins: stale CRM vs newer Docs note ----
        _field("orpheon.renewal.crm", "Orpheon Group", "renewal_date", "2026-05-02",
               asserted_at="2026-01-12T09:00:00Z"),
        _prose("orpheon.renewal.note", "Orpheon Group", "renewal_date", "2026-07-19",
               "Orpheon's renewal moved to {value} after the legal review.",
               asserted_at="2026-03-28T11:00:00Z"),
        _field("veltrix.seats.crm", "Veltrix Labs", "seat_count", 250,
               asserted_at="2025-12-01T09:00:00Z"),
        _prose("veltrix.seats.note", "Veltrix Labs", "seat_count", 410,
               "The February QBR confirmed Veltrix Labs is now at {value} seats.",
               asserted_at="2026-02-19T16:00:00Z"),
        _field("halcyon.discount.crm", "Halcyon Foods", "discount_rate", "12%",
               asserted_at="2026-01-05T09:00:00Z"),
        _prose("halcyon.discount.memo", "Halcyon Foods", "discount_rate", "9%",
               "Pricing memo: Halcyon's discount stepped down to {value} for the new term.",
               asserted_at="2026-03-11T10:00:00Z"),
        _field("bluepine.contact.crm", "Bluepine Logistics", "primary_contact",
               "Marta Villas", asserted_at="2025-10-20T09:00:00Z"),
        _prose("bluepine.contact.note", "Bluepine Logistics", "primary_contact",
               "Jonas Brek", "Handover note: {value} is now Bluepine's primary contact.",
               asserted_at="2026-04-02T09:30:00Z"),

        # ---- resolvable, authority_wins: the binding doc is OLDER (recency misleads) ----
        _prose("kovacs.value.order", "Kovacs Industrial", "contract_value", "$2.86M",
               "The countersigned order form sets the Kovacs contract value at {value}; "
               "it supersedes any CRM estimate.",
               asserted_at="2026-01-15T09:00:00Z", authority=3),
        _field("kovacs.value.crm", "Kovacs Industrial", "contract_value", "$2.4M",
               asserted_at="2026-02-20T09:00:00Z", authority=1),
        _prose("northgate.region.dpa", "Northgate Medical", "data_region", "EU-Frankfurt",
               "The signed DPA fixes Northgate's data region to {value}; the DPA "
               "overrides any CRM field.",
               asserted_at="2026-01-08T09:00:00Z", authority=3),
        _field("northgate.region.crm", "Northgate Medical", "data_region", "US-Ohio",
               asserted_at="2026-03-02T09:00:00Z", authority=1),

        # ---- unresolvable: same timestamp, equal authority, no precedence signal ----
        _field("arcadia.value.crm", "Arcadia Systems", "contract_value", "$1.37M",
               asserted_at="2026-03-15T09:00:00Z", authority=1),
        _prose("arcadia.value.sheet", "Arcadia Systems", "contract_value", "$1.59M",
               "Finance tracker: the Arcadia contract value stands at {value}.",
               asserted_at="2026-03-15T09:00:00Z", authority=1),
        _field("orpheon.seats.crm", "Orpheon Group", "seat_count", 96,
               asserted_at="2026-02-27T10:00:00Z", authority=1),
        _prose("orpheon.seats.sheet", "Orpheon Group", "seat_count", 130,
               "Capacity sheet: Orpheon is provisioned for {value} seats.",
               asserted_at="2026-02-27T10:00:00Z", authority=1),
        _field("quill.renewal.crm", "Quill & Quarry", "renewal_date", "2026-09-04",
               asserted_at="2026-04-09T09:00:00Z", authority=1),
        _prose("quill.renewal.tracker", "Quill & Quarry", "renewal_date", "2026-11-22",
               "Renewal tracker: Quill & Quarry renews on {value}.",
               asserted_at="2026-04-09T09:00:00Z", authority=1),
        _field("tessitura.discount.crm", "Tessitura SpA", "discount_rate", "7%",
               asserted_at="2026-01-21T09:00:00Z", authority=1),
        _prose("tessitura.discount.card", "Tessitura SpA", "discount_rate", "11%",
               "Rate card: Tessitura SpA's discount is {value}.",
               asserted_at="2026-01-21T09:00:00Z", authority=1),
        _field("calder.terms.crm", "Calder & Sons", "payment_terms", "net-30",
               asserted_at="2026-02-14T09:00:00Z", authority=1),
        _prose("calder.terms.note", "Calder & Sons", "payment_terms", "net-60",
               "AP note: Calder & Sons pays on {value} terms.",
               asserted_at="2026-02-14T09:00:00Z", authority=1),

        # ---- filler: realistic record width + search noise (never probed) ----
        _field("veltrix.industry.crm", "Veltrix Labs", "industry", "biotech tooling"),
        _field("orpheon.industry.crm", "Orpheon Group", "industry", "media analytics"),
        _field("bluepine.industry.crm", "Bluepine Logistics", "industry",
               "cold-chain logistics"),
        _field("halcyon.industry.crm", "Halcyon Foods", "industry", "specialty foods"),
        _field("kovacs.industry.crm", "Kovacs Industrial", "industry",
               "industrial fasteners"),
        _field("northgate.industry.crm", "Northgate Medical", "industry",
               "clinical devices"),
        _field("arcadia.industry.crm", "Arcadia Systems", "industry",
               "workflow software"),
        _field("quill.industry.crm", "Quill & Quarry", "industry",
               "publishing services"),
        _field("tessitura.industry.crm", "Tessitura SpA", "industry",
               "textile machinery"),
        _field("calder.industry.crm", "Calder & Sons", "industry", "marine fittings"),
        _prose("ops.freeze.docs", "Calder & Sons", "deployment_freeze", "December",
               "Calder & Sons observes a deployment freeze each {value}."),
        _prose("ops.escalation.docs", "Sev-1 escalations", "page_window", "30 minutes",
               "Sev-1 escalations page the on-call within {value}."),
        _prose("pricing.signoff.docs", "pricing policy", "signoff_threshold", "3%",
               "Discounts below {value} require CFO sign-off."),
    ]

    A, R = ExpectedBehavior.answer, ExpectedBehavior.refuse
    probes = [
        # ---- none (6) ----
        Probe(probe_id="q_veltrix_response", conflict_type=ConflictType.none,
              question="Within how many hours does Veltrix Labs get a first support response?",
              references=["veltrix.plan.crm", "plan.prime7.docs"],
              expected_behavior=A, expected_answer="7 hours",
              expected_sources=["veltrix.plan.crm", "plan.prime7.docs"]),
        Probe(probe_id="q_bluepine_countersign", conflict_type=ConflictType.none,
              question="Who countersigns Bluepine Logistics' renewal orders?",
              references=["bluepine.manager.crm", "bluepine.countersign.docs"],
              expected_behavior=A, expected_answer="Dana Okafor",
              expected_sources=["bluepine.manager.crm", "bluepine.countersign.docs"]),
        Probe(probe_id="q_halcyon_surcharge", conflict_type=ConflictType.none,
              question="What monthly surcharge applies to Halcyon Foods' late invoices?",
              references=["halcyon.terms.crm", "terms.net45.docs"],
              expected_behavior=A, expected_answer="1.8%",
              expected_sources=["halcyon.terms.crm", "terms.net45.docs"]),
        Probe(probe_id="q_kovacs_hub", conflict_type=ConflictType.none,
              question="From which hub do Kovacs Industrial dispatches ship?",
              references=["kovacs.region.crm", "region.4east.docs"],
              expected_behavior=A, expected_answer="Brno",
              expected_sources=["kovacs.region.crm", "region.4east.docs"]),
        Probe(probe_id="q_northgate_cap", conflict_type=ConflictType.none,
              question="What is the per-incident liability cap for Northgate Medical?",
              references=["northgate.contractform.crm", "msa2024.cap.docs"],
              expected_behavior=A, expected_answer="$425k",
              expected_sources=["northgate.contractform.crm", "msa2024.cap.docs"]),
        Probe(probe_id="q_arcadia_triage", conflict_type=ConflictType.none,
              question="Within how many minutes are Arcadia Systems' tickets triaged?",
              references=["arcadia.plan.crm", "plan.juniper.docs"],
              expected_behavior=A, expected_answer="90 minutes",
              expected_sources=["arcadia.plan.crm", "plan.juniper.docs"]),

        # ---- resolvable (6: 4 recency + 2 authority) ----
        Probe(probe_id="q_orpheon_renewal", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.recency_wins,
              question="When is Orpheon Group's renewal date?",
              references=["orpheon.renewal.crm", "orpheon.renewal.note"],
              expected_behavior=A, expected_answer="2026-07-19",
              expected_sources=["orpheon.renewal.crm", "orpheon.renewal.note"]),
        Probe(probe_id="q_veltrix_seats", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.recency_wins,
              question="How many seats does Veltrix Labs have?",
              references=["veltrix.seats.crm", "veltrix.seats.note"],
              expected_behavior=A, expected_answer="410",
              expected_sources=["veltrix.seats.crm", "veltrix.seats.note"]),
        Probe(probe_id="q_halcyon_discount", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.recency_wins,
              question="What discount rate does Halcyon Foods currently get?",
              references=["halcyon.discount.crm", "halcyon.discount.memo"],
              expected_behavior=A, expected_answer="9%",
              expected_sources=["halcyon.discount.crm", "halcyon.discount.memo"]),
        Probe(probe_id="q_bluepine_contact", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.recency_wins,
              question="Who is Bluepine Logistics' primary contact?",
              references=["bluepine.contact.crm", "bluepine.contact.note"],
              expected_behavior=A, expected_answer="Jonas Brek",
              expected_sources=["bluepine.contact.crm", "bluepine.contact.note"]),
        Probe(probe_id="q_kovacs_value", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.authority_wins,
              question="What is Kovacs Industrial's contract value?",
              references=["kovacs.value.order", "kovacs.value.crm"],
              expected_behavior=A, expected_answer="$2.86M",
              expected_sources=["kovacs.value.order", "kovacs.value.crm"]),
        Probe(probe_id="q_northgate_region", conflict_type=ConflictType.resolvable,
              resolution_rule=ResolutionRule.authority_wins,
              question="In which data region is Northgate Medical's data hosted?",
              references=["northgate.region.dpa", "northgate.region.crm"],
              expected_behavior=A, expected_answer="EU-Frankfurt",
              expected_sources=["northgate.region.dpa", "northgate.region.crm"]),

        # ---- unresolvable (5) ----
        Probe(probe_id="q_arcadia_value", conflict_type=ConflictType.unresolvable,
              question="What is Arcadia Systems' contract value?",
              references=["arcadia.value.crm", "arcadia.value.sheet"],
              expected_behavior=R, expected_answer=None,
              expected_sources=["arcadia.value.crm", "arcadia.value.sheet"]),
        Probe(probe_id="q_orpheon_seats", conflict_type=ConflictType.unresolvable,
              question="How many seats does Orpheon Group have?",
              references=["orpheon.seats.crm", "orpheon.seats.sheet"],
              expected_behavior=R, expected_answer=None,
              expected_sources=["orpheon.seats.crm", "orpheon.seats.sheet"]),
        Probe(probe_id="q_quill_renewal", conflict_type=ConflictType.unresolvable,
              question="When does Quill & Quarry's contract renew?",
              references=["quill.renewal.crm", "quill.renewal.tracker"],
              expected_behavior=R, expected_answer=None,
              expected_sources=["quill.renewal.crm", "quill.renewal.tracker"]),
        Probe(probe_id="q_tessitura_discount", conflict_type=ConflictType.unresolvable,
              question="What discount rate does Tessitura SpA get?",
              references=["tessitura.discount.crm", "tessitura.discount.card"],
              expected_behavior=R, expected_answer=None,
              expected_sources=["tessitura.discount.crm", "tessitura.discount.card"]),
        Probe(probe_id="q_calder_terms", conflict_type=ConflictType.unresolvable,
              question="On what payment terms does Calder & Sons pay?",
              references=["calder.terms.crm", "calder.terms.note"],
              expected_behavior=R, expected_answer=None,
              expected_sources=["calder.terms.crm", "calder.terms.note"]),

        # ---- void (5): plausible questions the org genuinely cannot answer ----
        Probe(probe_id="q_veltrix_billing", conflict_type=ConflictType.void,
              question="What is Veltrix Labs' billing address?",
              references=[], expected_behavior=R, expected_answer=None,
              expected_sources=[]),
        Probe(probe_id="q_halcyon_sponsor", conflict_type=ConflictType.void,
              question="Who is the executive sponsor for Halcyon Foods?",
              references=[], expected_behavior=R, expected_answer=None,
              expected_sources=[]),
        Probe(probe_id="q_quill_plan", conflict_type=ConflictType.void,
              question="What support plan is Quill & Quarry on?",
              references=[], expected_behavior=R, expected_answer=None,
              expected_sources=[]),
        Probe(probe_id="q_bluepine_penalty", conflict_type=ConflictType.void,
              question="What early-termination penalty applies to Bluepine Logistics?",
              references=[], expected_behavior=R, expected_answer=None,
              expected_sources=[]),
        Probe(probe_id="q_tessitura_seats", conflict_type=ConflictType.void,
              question="How many seats does Tessitura SpA have?",
              references=[], expected_behavior=R, expected_answer=None,
              expected_sources=[]),
    ]
    return Blueprint(claims=claims, probes=probes)
