/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blueprints */
        get: operations["list_blueprints_api_blueprints_get"];
        put?: never;
        /** Create Blueprint */
        post: operations["create_blueprint_api_blueprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Blueprint
         * @description Compile in memory and return the resulting org (CRM db.json, docs, manifest) —
         *     no disk write, no eval. Powers the editor's live preview.
         */
        post: operations["preview_blueprint_api_blueprints_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Blueprint */
        post: operations["validate_blueprint_api_blueprints_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/{blueprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blueprint */
        get: operations["get_blueprint_api_blueprints__blueprint_id__get"];
        /** Upsert Blueprint */
        put: operations["upsert_blueprint_api_blueprints__blueprint_id__put"];
        post?: never;
        /** Delete Blueprint */
        delete: operations["delete_blueprint_api_blueprints__blueprint_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Catalog */
        get: operations["catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Comparison */
        post: operations["create_comparison_api_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Provider */
        put: operations["save_provider_api_providers__provider_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Run history with verdicts but without heavyweight reports and receipts.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/dry-run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dry Run */
        post: operations["dry_run_api_runs_dry_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Run */
        post: operations["import_run_api_runs_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Run */
        post: operations["archive_run_api_runs__run_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-Sent Events stream of run status until terminal. SSE (not WebSocket) is
         *     simpler and more air-gap-friendly; the FE shows live status off this.
         */
        get: operations["run_events_api_runs__run_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchiveRequest */
        ArchiveRequest: {
            /**
             * Archived
             * @default true
             */
            archived: boolean;
        };
        /** Artifacts */
        Artifacts: {
            /** Docs */
            docs: components["schemas"]["DocFile"][];
            /** Manifest */
            manifest: {
                [key: string]: components["schemas"]["ManifestEntry"];
            };
            /** Silos */
            silos: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: components["schemas"]["SiloField"];
                    };
                };
            };
        };
        /** Blocker */
        Blocker: {
            /**
             * Code
             * @enum {string}
             */
            code: "unknown_suite" | "not_connected" | "grader_required" | "grader_not_allowed" | "self_grading" | "unknown_scaffold" | "unknown_provider" | "empty_suite";
            /** Fix */
            fix: string | null;
            /** Message */
            message: string;
        };
        /**
         * Blueprint
         * @description A fragmented organization: the claims it knows and the probes we ask it.
         */
        Blueprint: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Probes */
            probes?: components["schemas"]["Probe"][];
        };
        /** BlueprintDeleted */
        BlueprintDeleted: {
            /** Deleted */
            deleted: string;
        };
        /** BlueprintId */
        BlueprintId: {
            /** Id */
            id: string;
        };
        /** BlueprintMeta */
        BlueprintMeta: {
            /** Claims */
            claims: number;
            /** Id */
            id: string;
            /** Probes */
            probes: number;
        };
        /** Body_import_run_api_runs_import_post */
        Body_import_run_api_runs_import_post: {
            /** File */
            file: string;
        };
        /** Catalog */
        Catalog: {
            defaults: components["schemas"]["Defaults"];
            /** Models */
            models: components["schemas"]["CatalogModel"][];
            /** Providers */
            providers: components["schemas"]["CatalogProvider"][];
            /** Scaffolds */
            scaffolds: string[];
            /** Scorers */
            scorers: components["schemas"]["CatalogScorer"][];
            /** Suites */
            suites: components["schemas"]["CatalogSuite"][];
        };
        /** CatalogModel */
        CatalogModel: {
            /** Connected */
            connected: boolean;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Provider */
            provider: string;
        };
        /** CatalogProvider */
        CatalogProvider: {
            /** Connected */
            connected: boolean;
            /** Fields */
            fields: components["schemas"]["CatalogProviderField"][];
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** CatalogProviderField */
        CatalogProviderField: {
            /** Env Var */
            env_var: string;
            /** Id */
            id: string;
        };
        /** CatalogScorer */
        CatalogScorer: {
            /**
             * Engine
             * @enum {string}
             */
            engine: "deterministic" | "llm";
            /** Version */
            version: string;
        };
        /** CatalogSuite */
        CatalogSuite: {
            /** Claims */
            claims: number;
            /** Editable */
            editable: boolean;
            /**
             * Kind
             * @enum {string}
             */
            kind: "builtin" | "user";
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Org */
            org: string;
            /** Questions */
            questions: number;
        };
        /** CategoryPairCounts */
        CategoryPairCounts: {
            /** A Wins */
            a_wins: number;
            /** B Wins */
            b_wins: number;
            /** Both Fail */
            both_fail: number;
            /** Both Pass */
            both_pass: number;
            /** Discordant */
            discordant: number;
            /** Dropped */
            dropped: string[];
            /** Key */
            key: string;
            /** Matched */
            matched: number;
            /** P Value */
            p_value: number;
        };
        /**
         * Claim
         * @description An atomic knowledge unit that lives in exactly one silo.
         */
        Claim: {
            /** Asserted At */
            asserted_at?: string | null;
            /** Authority */
            authority?: number | null;
            /** Claim Id */
            claim_id: string;
            /** Predicate */
            predicate: string;
            render: components["schemas"]["Render"];
            /** Silo */
            silo: string;
            /** Subject */
            subject: string;
            /** Value */
            value: unknown;
        };
        /** ComparisonDiagnostics */
        ComparisonDiagnostics: {
            /** A */
            a: components["schemas"]["Diagnostic"][];
            /** B */
            b: components["schemas"]["Diagnostic"][];
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** A */
            a: string;
            /** B */
            b: string;
            /**
             * Intervention
             * @default model
             * @enum {string}
             */
            intervention: "model" | "org" | "engine" | "grader" | "k" | "scaffold" | "seed" | "harness";
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Categories */
            categories: components["schemas"]["CategoryPairCounts"][];
            /** Changed Dimensions */
            changed_dimensions: string[];
            /** Compatible */
            compatible: boolean;
            diagnostics: components["schemas"]["ComparisonDiagnostics"];
            /** Intervention */
            intervention: string;
            overall: components["schemas"]["PairCounts"];
            /** Unexpected Dimensions */
            unexpected_dimensions: string[];
        };
        /**
         * ConflictType
         * @description The four-way taxonomy at the heart of the eval: what kind of disagreement (if
         *     any) the silos hold for a probe. It decides whether the right move is to answer or
         *     to refuse, and `unresolvable` is the column that actually separates reliable agents
         *     from confident fabricators.
         * @enum {string}
         */
        ConflictType: "none" | "resolvable" | "unresolvable" | "void";
        /** Defaults */
        Defaults: {
            /**
             * Engine
             * @default deterministic
             * @enum {string}
             */
            engine: "deterministic" | "llm";
            /**
             * K
             * @default 3
             */
            k: number;
            /**
             * Scaffold
             * @default baseline
             */
            scaffold: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Suite
             * @default starter
             */
            suite: string;
        };
        /**
         * Diagnostic
         * @description One aggregated failure signature from report.compare.diagnose_report.
         */
        Diagnostic: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string;
        };
        /** DocFile */
        DocFile: {
            /** Content */
            content: string;
            /** Path */
            path: string;
        };
        /**
         * ExpectedBehavior
         * @description What a correct agent does on this probe — the outcome the scorer grades against.
         * @enum {string}
         */
        ExpectedBehavior: "answer" | "refuse";
        /** Gate */
        Gate: {
            /** Min Pass K */
            min_pass_k: number;
            /** Passed */
            passed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Artifact */
            artifact: string;
            /** Locator */
            locator: string;
            /** Predicate */
            predicate: string;
            /** Silo */
            silo: string;
            /** Subject */
            subject: string;
        };
        /** PairCounts */
        PairCounts: {
            /** A Wins */
            a_wins: number;
            /** B Wins */
            b_wins: number;
            /** Both Fail */
            both_fail: number;
            /** Both Pass */
            both_pass: number;
            /** Discordant */
            discordant: number;
            /** Dropped */
            dropped: string[];
            /** Matched */
            matched: number;
            /** P Value */
            p_value: number;
        };
        /** Plan */
        Plan: {
            /** Blockers */
            blockers: components["schemas"]["Blocker"][];
            /** Diagnostics */
            diagnostics: string[];
            /** Provider */
            provider: string | null;
            /** Ready */
            ready: boolean;
            request: components["schemas"]["RunSpec"];
            /** Scorer Version */
            scorer_version: string | null;
            suite: components["schemas"]["CatalogSuite"] | null;
        };
        /**
         * Probe
         * @description A question that references claims and declares expected behavior.
         */
        Probe: {
            conflict_type: components["schemas"]["ConflictType"];
            /** Expected Answer */
            expected_answer?: string | null;
            expected_behavior: components["schemas"]["ExpectedBehavior"];
            /** Expected Sources */
            expected_sources?: string[];
            /** Probe Id */
            probe_id: string;
            /** Question */
            question: string;
            /** References */
            references?: string[];
            resolution_rule?: components["schemas"]["ResolutionRule"] | null;
        };
        /** Provider */
        Provider: {
            /** Configured */
            configured: boolean;
            /** Fields */
            fields: components["schemas"]["ProviderField"][];
            /** Id */
            id: string;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "configured" | "needs_config";
        };
        /** ProviderField */
        ProviderField: {
            /** Configured */
            configured: boolean;
            /** Env Var */
            env_var: string;
            /** Id */
            id: string;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ReceiptArtifact */
        ReceiptArtifact: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string | null;
        };
        /** ReceiptProtocol */
        ReceiptProtocol: {
            /** Blueprint Sha256 */
            blueprint_sha256: string | null;
            /** Engine */
            engine: string;
            /** Epochs */
            epochs: number;
            /** Grader */
            grader: string | null;
            /** Harness */
            harness: string | null;
            /** Org */
            org: string | null;
            /** Scaffold */
            scaffold: string | null;
            /** Scorer Version */
            scorer_version: string | null;
            /** Seed */
            seed: number | null;
        };
        /** ReceiptRuntime */
        ReceiptRuntime: {
            /** Effective Models */
            effective_models: string[];
            /** Git Dirty */
            git_dirty: boolean | null;
            /** Git Revision */
            git_revision: string | null;
            /** Inspect Ai Version */
            inspect_ai_version: string | null;
            /** Reported Model */
            reported_model: string;
            /** Requested Model */
            requested_model: string;
            /** Tessera Version */
            tessera_version: string | null;
        };
        /** ReceiptTiming */
        ReceiptTiming: {
            /** Completed At */
            completed_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Started At */
            started_at: string | null;
        };
        /** ReceiptUsage */
        ReceiptUsage: {
            /** Billed Cost */
            billed_cost: number | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /**
         * Render
         * @description Rendering directive for a claim. ``as`` is aliased (Python keyword).
         */
        Render: {
            as: components["schemas"]["RenderAs"];
            /** Template */
            template?: string | null;
        };
        /**
         * RenderAs
         * @description How a claim is materialized into its silo.
         * @enum {string}
         */
        RenderAs: "field" | "prose";
        /** Report */
        Report: {
            axes: components["schemas"]["ReportAxes"];
            /** Categories */
            categories: components["schemas"]["ReportCategory"][];
            header: components["schemas"]["ReportHeader"];
            overall: components["schemas"]["ReportOverall"];
            /** Probes */
            probes: components["schemas"]["ReportProbe"][];
        };
        /** ReportAxes */
        ReportAxes: {
            /** Accuracy Rate */
            accuracy_rate: number | null;
            /** Answer Format Rate */
            answer_format_rate?: number | null;
            /** N Answer Epochs */
            n_answer_epochs: number;
            /** N Refuse Epochs */
            n_refuse_epochs: number;
            /** N Total Epochs */
            n_total_epochs: number;
            /** Provenance Rate */
            provenance_rate: number;
            /** Refusal Rate */
            refusal_rate: number | null;
        };
        /** ReportCategory */
        ReportCategory: {
            /** Flaky */
            flaky: boolean;
            /** Key */
            key: string;
            /** Mean Rate */
            mean_rate: number;
            /** N Probes */
            n_probes: number;
            /** Pass K Rate */
            pass_k_rate: number;
        };
        /** ReportFailure */
        ReportFailure: {
            /** Accuracy Ok */
            accuracy_ok: boolean;
            /** Answer */
            answer: string;
            /** Answer Format Ok */
            answer_format_ok?: boolean | null;
            /** Consulted */
            consulted: string[];
            /** Epoch */
            epoch: number;
            /** Expected Sources */
            expected_sources: string[];
            /** Missing */
            missing: string[];
            /** Passed */
            passed: boolean;
            /** Provenance Ok */
            provenance_ok: boolean;
            /** Question */
            question: string;
            /** Refusal Ok */
            refusal_ok: boolean;
        };
        /** ReportHeader */
        ReportHeader: {
            /** Created */
            created: string;
            /** Engine */
            engine: string;
            /** Grader */
            grader: string | null;
            /** Harness */
            harness?: string | null;
            /** Inspect Ai Version */
            inspect_ai_version?: string | null;
            /** K */
            k: number;
            /** Location */
            location: string;
            /** Model */
            model: string;
            /** Org */
            org: string | null;
            /** Scaffold */
            scaffold?: string | null;
            /** Scorer Version */
            scorer_version?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** ReportOverall */
        ReportOverall: {
            /** Mean Rate */
            mean_rate: number;
            /** Pass K Rate */
            pass_k_rate: number;
        };
        /** ReportProbe */
        ReportProbe: {
            /** Conflict Type */
            conflict_type: string;
            /** Epochs Passed */
            epochs_passed: number;
            /** Epochs Total */
            epochs_total: number;
            /** Expected Behavior */
            expected_behavior: string;
            /** Failures */
            failures: components["schemas"]["ReportFailure"][];
            /** Mean Pass */
            mean_pass: number;
            /** Pass K */
            pass_k: boolean;
            /** Probe Id */
            probe_id: string;
        };
        /**
         * ResolutionRule
         * @description How a `resolvable` conflict is decided. Note authority can outrank recency: a
         *     source that declares itself binding wins even over a fresher one.
         * @enum {string}
         */
        ResolutionRule: "recency_wins" | "authority_wins";
        /** Run */
        Run: {
            /** Archived */
            archived: boolean;
            /** Created At */
            created_at: string;
            /** Diagnostics */
            diagnostics: components["schemas"]["Diagnostic"][];
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            gate: components["schemas"]["Gate"] | null;
            /** Id */
            id: string;
            /** Ok */
            ok: boolean;
            paths: components["schemas"]["RunPaths"];
            receipt: components["schemas"]["RunReceipt"] | null;
            report: components["schemas"]["Report"] | null;
            request: components["schemas"]["RunRequestSpec"];
            /** Schema Version */
            schema_version: number;
            /**
             * Source
             * @enum {string}
             */
            source: "run" | "import" | "bundled";
            /** Started At */
            started_at: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "completed" | "failed" | "interrupted";
            verdict: components["schemas"]["Verdict"] | null;
        };
        /** RunPaths */
        RunPaths: {
            /** Dir */
            dir: string;
            /** Log */
            log: string | null;
            /** Report Json */
            report_json: string | null;
            /** Report Md */
            report_md: string | null;
        };
        /** RunReceipt */
        RunReceipt: {
            artifact: components["schemas"]["ReceiptArtifact"];
            /** Execution Hash */
            execution_hash: string;
            protocol: components["schemas"]["ReceiptProtocol"];
            /** Protocol Hash */
            protocol_hash: string;
            runtime: components["schemas"]["ReceiptRuntime"];
            timing: components["schemas"]["ReceiptTiming"];
            usage: components["schemas"]["ReceiptUsage"];
        };
        /** RunRequestSpec */
        RunRequestSpec: {
            /**
             * Engine
             * @enum {string}
             */
            engine: "deterministic" | "llm";
            /** Grader */
            grader: string | null;
            /** K */
            k: number;
            /** Model */
            model: string;
            /** Scaffold */
            scaffold: string;
            /** Seed */
            seed: number;
            /** Suite */
            suite: string;
        };
        /**
         * RunSpec
         * @description The request as a user writes it: RunRequestSpec plus defaults and input bounds.
         *     Shape only — the grader/engine and suite rules are runner.plan's blockers.
         */
        RunSpec: {
            /**
             * Engine
             * @default deterministic
             * @enum {string}
             */
            engine: "deterministic" | "llm";
            /** Grader */
            grader?: string | null;
            /**
             * K
             * @default 3
             */
            k: number;
            /** Model */
            model: string;
            /**
             * Scaffold
             * @default baseline
             */
            scaffold: string;
            /**
             * Seed
             * @default 0
             */
            seed: number;
            /**
             * Suite
             * @default starter
             */
            suite: string;
        };
        /** SiloField */
        SiloField: {
            /** Asserted At */
            asserted_at: string | null;
            /** Value */
            value: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Ok */
            ok: boolean;
        };
        /** Verdict */
        Verdict: {
            /**
             * Label
             * @enum {string}
             */
            label: "reliable" | "inconsistent" | "unreliable";
            /** Mean Rate */
            mean_rate: number;
            /** Pass K Rate */
            pass_k_rate: number;
            /** Sentence */
            sentence: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_blueprints_api_blueprints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintMeta"][];
                };
            };
        };
    };
    create_blueprint_api_blueprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_blueprint_api_blueprints_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_blueprint_api_blueprints_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprint_api_blueprints__blueprint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_blueprint_api_blueprints__blueprint_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blueprint_api_blueprints__blueprint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintDeleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    create_comparison_api_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    save_provider_api_providers__provider_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dry_run_api_runs_dry_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunSpec"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_run_api_runs_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_run_api_runs_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_run_api_runs__run_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Run"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__run_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
