/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blueprints */
        get: operations["list_blueprints_api_blueprints_get"];
        put?: never;
        /** Create Blueprint */
        post: operations["create_blueprint_api_blueprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Blueprint
         * @description Compile in memory and return the resulting org (CRM db.json, docs, manifest) —
         *     no disk write, no eval. Powers the editor's live preview.
         */
        post: operations["preview_blueprint_api_blueprints_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Blueprint */
        post: operations["validate_blueprint_api_blueprints_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/{blueprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blueprint */
        get: operations["get_blueprint_api_blueprints__blueprint_id__get"];
        /** Upsert Blueprint */
        put: operations["upsert_blueprint_api_blueprints__blueprint_id__put"];
        post?: never;
        /** Delete Blueprint */
        delete: operations["delete_blueprint_api_blueprints__blueprint_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/comparisons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Comparison */
        post: operations["create_comparison_api_comparisons_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Setup
         * @description Return the typed, credential-safe vocabulary and defaults for the eval launcher.
         */
        get: operations["eval_setup_api_eval_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Evaluations */
        get: operations["list_evaluations_api_evaluations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Evaluation */
        post: operations["import_evaluation_api_evaluations_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Diagnostics */
        get: operations["evaluation_diagnostics_api_evaluations__evaluation_id__diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluations/{evaluation_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluation Report */
        get: operations["evaluation_report_api_evaluations__evaluation_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Experiments */
        get: operations["list_experiments_api_experiments_get"];
        put?: never;
        /** Start Experiment */
        post: operations["start_experiment_api_experiments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Experiment */
        get: operations["get_experiment_api_experiments__experiment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/comparisons/{variant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Experiment Comparison */
        get: operations["experiment_comparison_api_experiments__experiment_id__comparisons__variant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/experiments/{experiment_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume Experiment */
        post: operations["resume_experiment_api_experiments__experiment_id__resume_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/leaderboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leaderboard
         * @description The committed public-leaderboard manifest served verbatim to the SPA.
         */
        get: operations["leaderboard_api_leaderboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{log_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_logs__log_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-discovery/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan */
        post: operations["rescan_api_model_discovery_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The published model set displayed by the Run form.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orgs
         * @description Runnable orgs = built-in ORGS builders + saved blueprints from the store, so a
         *     dataset authored on the Datasets page is immediately runnable here. Raises (500)
         *     if a custom org module fails to import — surfaced by the frontend as a warning.
         */
        get: operations["list_orgs_api_orgs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/preflights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Preflight */
        post: operations["run_preflight_api_preflights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Provider */
        put: operations["save_provider_api_providers__provider_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Report */
        post: operations["upload_report_api_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Run history (newest first) with headline rates — for the monitor + dashboard.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Run */
        post: operations["archive_run_api_runs__job_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-Sent Events stream of run status until terminal. SSE (not WebSocket) is
         *     simpler and more air-gap-friendly; the FE shows live status off this.
         */
        get: operations["run_events_api_runs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trends
         * @description Time-ordered series across finished runs (optionally filtered) for the dashboard:
         *     pass^k/mean overall, per-conflict pass^k, and the three axes.
         */
        get: operations["trends_api_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ArchiveRequest */
        ArchiveRequest: {
            /**
             * Archived
             * @default true
             */
            archived: boolean;
        };
        /** Artifacts */
        Artifacts: {
            /** Docs */
            docs: components["schemas"]["DocFile"][];
            /** Manifest */
            manifest: {
                [key: string]: components["schemas"]["ManifestEntry"];
            };
            /** Silos */
            silos: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: components["schemas"]["SiloField"];
                    };
                };
            };
        };
        /**
         * Blueprint
         * @description A fragmented organization: the claims it knows and the probes we ask it.
         */
        Blueprint: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Probes */
            probes?: components["schemas"]["Probe"][];
        };
        /** BlueprintDeleted */
        BlueprintDeleted: {
            /** Deleted */
            deleted: string;
        };
        /** BlueprintId */
        BlueprintId: {
            /** Id */
            id: string;
        };
        /** BlueprintMeta */
        BlueprintMeta: {
            /** Claims */
            claims: number;
            /** Id */
            id: string;
            /** Probes */
            probes: number;
        };
        /** Body_import_evaluation_api_evaluations_import_post */
        Body_import_evaluation_api_evaluations_import_post: {
            /** File */
            file: string;
        };
        /** Body_upload_report_api_reports_post */
        Body_upload_report_api_reports_post: {
            /** File */
            file: string;
        };
        /** CategoryPairCounts */
        CategoryPairCounts: {
            /** A Wins */
            a_wins: number;
            /** B Wins */
            b_wins: number;
            /** Both Fail */
            both_fail: number;
            /** Both Pass */
            both_pass: number;
            /** Discordant */
            discordant: number;
            /** Dropped */
            dropped: string[];
            /** Key */
            key: string;
            /** Matched */
            matched: number;
            /** P Value */
            p_value: number;
        };
        /**
         * Claim
         * @description An atomic knowledge unit that lives in exactly one silo.
         */
        Claim: {
            /** Asserted At */
            asserted_at?: string | null;
            /** Authority */
            authority?: number | null;
            /** Claim Id */
            claim_id: string;
            /** Predicate */
            predicate: string;
            render: components["schemas"]["Render"];
            /** Silo */
            silo: string;
            /** Subject */
            subject: string;
            /** Value */
            value: unknown;
        };
        /** ComparisonDiagnostics */
        ComparisonDiagnostics: {
            /** A */
            a: components["schemas"]["Diagnostic"][];
            /** B */
            b: components["schemas"]["Diagnostic"][];
        };
        /** ComparisonRequest */
        ComparisonRequest: {
            /** Evaluation A */
            evaluation_a: string;
            /** Evaluation B */
            evaluation_b: string;
            /**
             * Intervention
             * @default model
             * @enum {string}
             */
            intervention: "model" | "org" | "engine" | "grader" | "k" | "scaffold" | "seed" | "harness";
        };
        /** ComparisonResult */
        ComparisonResult: {
            /** Categories */
            categories: components["schemas"]["CategoryPairCounts"][];
            /** Changed Dimensions */
            changed_dimensions: string[];
            /** Compatible */
            compatible: boolean;
            diagnostics: components["schemas"]["ComparisonDiagnostics"];
            /** Intervention */
            intervention: string;
            overall: components["schemas"]["PairCounts"];
            /** Unexpected Dimensions */
            unexpected_dimensions: string[];
        };
        /**
         * ConflictType
         * @description The four-way taxonomy at the heart of the eval: what kind of disagreement (if
         *     any) the silos hold for a probe. It decides whether the right move is to answer or
         *     to refuse, and `unresolvable` is the column that actually separates reliable agents
         *     from confident fabricators.
         * @enum {string}
         */
        ConflictType: "none" | "resolvable" | "unresolvable" | "void";
        /**
         * Diagnostic
         * @description One aggregated failure signature from report.compare.diagnose_report.
         */
        Diagnostic: {
            /** Count */
            count: number;
            /** Kind */
            kind: string;
            /** Signature */
            signature: string;
        };
        /** DocFile */
        DocFile: {
            /** Content */
            content: string;
            /** Path */
            path: string;
        };
        /** EvalSetup */
        EvalSetup: {
            defaults: components["schemas"]["EvalSetupDefaults"];
            /** Models */
            models: components["schemas"]["EvalSetupModel"][];
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
            /** Suites */
            suites: components["schemas"]["EvalSetupSuite"][];
        };
        /** EvalSetupDefaults */
        EvalSetupDefaults: {
            /**
             * Engine
             * @constant
             */
            engine: "deterministic";
            /** Grader */
            grader: string | null;
            /** Repeats */
            repeats: number;
        };
        /** EvalSetupModel */
        EvalSetupModel: {
            /** Detail */
            detail?: string | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Provider */
            provider: string;
            /** Published */
            published: boolean;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "ready" | "needs_config" | "needs_server" | "offline" | "unverified";
            /** Released */
            released: string | null;
            /** Retired */
            retired: boolean;
            /** Source */
            source: string;
        };
        /** EvalSetupSuite */
        EvalSetupSuite: {
            /** Claims */
            claims: number;
            /** Editable */
            editable: boolean;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "builtin" | "custom";
            /** Questions */
            questions: number;
        };
        /** EvaluationSummary */
        EvaluationSummary: {
            /** Artifact Path */
            artifact_path: string | null;
            /** Artifact Sha256 */
            artifact_sha256: string | null;
            /** Created At */
            created_at: string;
            /** Engine */
            engine: string;
            /** Epochs */
            epochs: number;
            /** Execution Hash */
            execution_hash: string;
            /** Grader */
            grader: string | null;
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "run" | "log" | "pinned" | "import";
            /** Mean Rate */
            mean_rate: number | null;
            /** Model */
            model: string;
            /** Org */
            org: string | null;
            /** Pass K Rate */
            pass_k_rate: number | null;
            /** Protocol Hash */
            protocol_hash: string;
            receipt: components["schemas"]["RunReceipt"];
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "done" | "error";
        };
        /**
         * ExpectedBehavior
         * @description What a correct agent does on this probe — the outcome the scorer grades against.
         * @enum {string}
         */
        ExpectedBehavior: "answer" | "refuse";
        /** Experiment */
        Experiment: {
            /** Baseline Variant */
            baseline_variant: string;
            /** Cells */
            cells: components["schemas"]["ExperimentCell"][];
            /** Created At */
            created_at: string;
            /** Error */
            error: string | null;
            /** Id */
            id: string;
            /** Name */
            name: string;
            request: components["schemas"]["ExperimentRequest"];
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error" | "stopped";
            /** Total Cost */
            total_cost: number | null;
            /** Updated At */
            updated_at: string;
        };
        /** ExperimentCell */
        ExperimentCell: {
            /** Error */
            error: string | null;
            /** Experiment Id */
            experiment_id: string;
            /** Id */
            id: string;
            /** Repeat Index */
            repeat_index: number;
            /** Run Id */
            run_id: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "error" | "skipped";
            /** Variant Id */
            variant_id: string;
        };
        /** ExperimentComparison */
        ExperimentComparison: {
            /** Categories */
            categories: components["schemas"]["CategoryPairCounts"][];
            /** Changed Dimensions */
            changed_dimensions: string[];
            /** Compatible */
            compatible: boolean;
            diagnostics: components["schemas"]["ComparisonDiagnostics"];
            /** Dropped Repeats */
            dropped_repeats: number[];
            /** Intervention */
            intervention: string;
            overall: components["schemas"]["PairCounts"];
            /** Paired Repeats */
            paired_repeats: number[];
            /** Unexpected Dimensions */
            unexpected_dimensions: string[];
        };
        /** ExperimentRequest */
        ExperimentRequest: {
            /** Baseline Variant */
            baseline_variant: string;
            /**
             * Intervention
             * @default model
             * @enum {string}
             */
            intervention: "model" | "org" | "engine" | "grader" | "k" | "scaffold" | "seed" | "harness";
            /**
             * Max Consecutive Errors
             * @default 3
             */
            max_consecutive_errors: number;
            /** Max Cost */
            max_cost?: number | null;
            /** Name */
            name: string;
            /**
             * Repeats
             * @default 1
             */
            repeats: number;
            /** Variants */
            variants: components["schemas"]["ExperimentVariant"][];
        };
        /** ExperimentStarted */
        ExperimentStarted: {
            /** Experiment Id */
            experiment_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error" | "stopped";
        };
        /** ExperimentVariant */
        ExperimentVariant: {
            /**
             * Epochs
             * @default 3
             */
            epochs: number;
            /** Grader */
            grader?: string | null;
            /** Id */
            id: string;
            /**
             * Judge
             * @default deterministic
             * @enum {string}
             */
            judge: "llm" | "deterministic";
            /** Label */
            label: string;
            /** Model */
            model: string;
            /**
             * Org
             * @default toy
             */
            org: string;
            /**
             * Scaffold
             * @default baseline
             * @enum {string}
             */
            scaffold: "baseline" | "refusal_aware";
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LeaderboardManifest */
        LeaderboardManifest: {
            /**
             * Exhibitions
             * @default []
             */
            exhibitions: {
                [key: string]: unknown;
            }[];
            /** Rows */
            rows: components["schemas"]["LeaderboardRow"][];
            /** Title */
            title?: string | null;
        };
        /** LeaderboardRow */
        LeaderboardRow: {
            /** Answer Format Rate */
            answer_format_rate?: number | null;
            /** Categories */
            categories: {
                [key: string]: number;
            };
            /** Date */
            date?: string | null;
            /** Harness */
            harness?: string | null;
            /** K */
            k: number;
            /** Label */
            label: string;
            /** Log */
            log?: string | null;
            /** Mean Rate */
            mean_rate: number;
            /** Model */
            model: string;
            /** Notes */
            notes?: string | null;
            /** Org */
            org?: string | null;
            /** Pass K Rate */
            pass_k_rate: number;
            /** Scaffold */
            scaffold?: string | null;
            /** Scorer Version */
            scorer_version?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** LogMeta */
        LogMeta: {
            /** Created */
            created: string;
            /** Engine */
            engine: string;
            /** Grader */
            grader: string | null;
            /** Id */
            id: string;
            /** K */
            k: number;
            /** Model */
            model: string;
            /** Org */
            org: string | null;
            /** Path */
            path: string;
            /** Source */
            source: string;
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Artifact */
            artifact: string;
            /** Locator */
            locator: string;
            /** Predicate */
            predicate: string;
            /** Silo */
            silo: string;
            /** Subject */
            subject: string;
        };
        /** PairCounts */
        PairCounts: {
            /** A Wins */
            a_wins: number;
            /** B Wins */
            b_wins: number;
            /** Both Fail */
            both_fail: number;
            /** Both Pass */
            both_pass: number;
            /** Discordant */
            discordant: number;
            /** Dropped */
            dropped: string[];
            /** Matched */
            matched: number;
            /** P Value */
            p_value: number;
        };
        /** PreflightRequest */
        PreflightRequest: {
            /** Model */
            model: string;
            /**
             * Refresh
             * @default false
             */
            refresh: boolean;
            /**
             * Require Tools
             * @default true
             */
            require_tools: boolean;
        };
        /** PreflightResult */
        PreflightResult: {
            /** Cached */
            cached: boolean;
            /** Checked At */
            checked_at: string;
            /** Effective Model */
            effective_model: string | null;
            /** Error */
            error: string | null;
            /** Latency Seconds */
            latency_seconds: number;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Tool Call */
            tool_call: boolean;
            usage: components["schemas"]["PreflightUsage"];
        };
        /** PreflightUsage */
        PreflightUsage: {
            /** Billed Cost */
            billed_cost: number | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /**
         * Probe
         * @description A question that references claims and declares expected behavior.
         */
        Probe: {
            conflict_type: components["schemas"]["ConflictType"];
            /** Expected Answer */
            expected_answer?: string | null;
            expected_behavior: components["schemas"]["ExpectedBehavior"];
            /** Expected Sources */
            expected_sources?: string[];
            /** Probe Id */
            probe_id: string;
            /** Question */
            question: string;
            /** References */
            references?: string[];
            resolution_rule?: components["schemas"]["ResolutionRule"] | null;
        };
        /** Provider */
        Provider: {
            /** Configured */
            configured: boolean;
            /** Fields */
            fields: components["schemas"]["ProviderField"][];
            /** Id */
            id: string;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "configured" | "needs_config";
        };
        /** ProviderField */
        ProviderField: {
            /** Configured */
            configured: boolean;
            /** Env Var */
            env_var: string;
            /** Id */
            id: string;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /** ReceiptArtifact */
        ReceiptArtifact: {
            /** Path */
            path: string;
            /** Sha256 */
            sha256: string | null;
        };
        /** ReceiptProtocol */
        ReceiptProtocol: {
            /** Blueprint Sha256 */
            blueprint_sha256: string | null;
            /** Engine */
            engine: string;
            /** Epochs */
            epochs: number;
            /** Grader */
            grader: string | null;
            /** Harness */
            harness: string | null;
            /** Org */
            org: string | null;
            /** Scaffold */
            scaffold: string | null;
            /** Scorer Version */
            scorer_version: string | null;
            /** Seed */
            seed: number | null;
        };
        /** ReceiptRuntime */
        ReceiptRuntime: {
            /** Effective Models */
            effective_models: string[];
            /** Git Dirty */
            git_dirty: boolean | null;
            /** Git Revision */
            git_revision: string | null;
            /** Inspect Ai Version */
            inspect_ai_version: string | null;
            /** Reported Model */
            reported_model: string;
            /** Requested Model */
            requested_model: string;
            /** Tessera Version */
            tessera_version: string | null;
        };
        /** ReceiptTiming */
        ReceiptTiming: {
            /** Completed At */
            completed_at: string | null;
            /** Duration Seconds */
            duration_seconds: number | null;
            /** Started At */
            started_at: string | null;
        };
        /** ReceiptUsage */
        ReceiptUsage: {
            /** Billed Cost */
            billed_cost: number | null;
            /** Input Tokens */
            input_tokens: number;
            /** Output Tokens */
            output_tokens: number;
            /** Total Tokens */
            total_tokens: number;
        };
        /**
         * Render
         * @description Rendering directive for a claim. ``as`` is aliased (Python keyword).
         */
        Render: {
            as: components["schemas"]["RenderAs"];
            /** Template */
            template?: string | null;
        };
        /**
         * RenderAs
         * @description How a claim is materialized into its silo.
         * @enum {string}
         */
        RenderAs: "field" | "prose";
        /** Report */
        Report: {
            axes: components["schemas"]["ReportAxes"];
            /** Categories */
            categories: components["schemas"]["ReportCategory"][];
            header: components["schemas"]["ReportHeader"];
            overall: components["schemas"]["ReportOverall"];
            /** Probes */
            probes: components["schemas"]["ReportProbe"][];
        };
        /** ReportAxes */
        ReportAxes: {
            /** Accuracy Rate */
            accuracy_rate: number | null;
            /** Answer Format Rate */
            answer_format_rate?: number | null;
            /** N Answer Epochs */
            n_answer_epochs: number;
            /** N Refuse Epochs */
            n_refuse_epochs: number;
            /** N Total Epochs */
            n_total_epochs: number;
            /** Provenance Rate */
            provenance_rate: number;
            /** Refusal Rate */
            refusal_rate: number | null;
        };
        /** ReportCategory */
        ReportCategory: {
            /** Flaky */
            flaky: boolean;
            /** Key */
            key: string;
            /** Mean Rate */
            mean_rate: number;
            /** N Probes */
            n_probes: number;
            /** Pass K Rate */
            pass_k_rate: number;
        };
        /** ReportFailure */
        ReportFailure: {
            /** Accuracy Ok */
            accuracy_ok: boolean;
            /** Answer */
            answer: string;
            /** Answer Format Ok */
            answer_format_ok?: boolean | null;
            /** Consulted */
            consulted: string[];
            /** Epoch */
            epoch: number;
            /** Expected Sources */
            expected_sources: string[];
            /** Missing */
            missing: string[];
            /** Passed */
            passed: boolean;
            /** Provenance Ok */
            provenance_ok: boolean;
            /** Question */
            question: string;
            /** Refusal Ok */
            refusal_ok: boolean;
        };
        /** ReportHeader */
        ReportHeader: {
            /** Created */
            created: string;
            /** Engine */
            engine: string;
            /** Grader */
            grader: string | null;
            /** Harness */
            harness?: string | null;
            /** Inspect Ai Version */
            inspect_ai_version?: string | null;
            /** K */
            k: number;
            /** Location */
            location: string;
            /** Model */
            model: string;
            /** Org */
            org: string | null;
            /** Scaffold */
            scaffold?: string | null;
            /** Scorer Version */
            scorer_version?: string | null;
            /** Seed */
            seed?: number | null;
        };
        /** ReportOverall */
        ReportOverall: {
            /** Mean Rate */
            mean_rate: number;
            /** Pass K Rate */
            pass_k_rate: number;
        };
        /** ReportProbe */
        ReportProbe: {
            /** Conflict Type */
            conflict_type: string;
            /** Epochs Passed */
            epochs_passed: number;
            /** Epochs Total */
            epochs_total: number;
            /** Expected Behavior */
            expected_behavior: string;
            /** Failures */
            failures: components["schemas"]["ReportFailure"][];
            /** Mean Pass */
            mean_pass: number;
            /** Pass K */
            pass_k: boolean;
            /** Probe Id */
            probe_id: string;
        };
        /** RescanResult */
        RescanResult: {
            /** Model Count */
            model_count: number;
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
        };
        /**
         * ResolutionRule
         * @description How a `resolvable` conflict is decided. Note authority can outrank recency: a
         *     source that declares itself binding wins even over a fresher one.
         * @enum {string}
         */
        ResolutionRule: "recency_wins" | "authority_wins";
        /** RunReceipt */
        RunReceipt: {
            artifact: components["schemas"]["ReceiptArtifact"];
            /** Execution Hash */
            execution_hash: string;
            protocol: components["schemas"]["ReceiptProtocol"];
            /** Protocol Hash */
            protocol_hash: string;
            runtime: components["schemas"]["ReceiptRuntime"];
            timing: components["schemas"]["ReceiptTiming"];
            usage: components["schemas"]["ReceiptUsage"];
        };
        /** RunRequest */
        RunRequest: {
            /**
             * Epochs
             * @default 3
             */
            epochs: number;
            /** Grader */
            grader?: string | null;
            /**
             * Judge
             * @default deterministic
             * @enum {string}
             */
            judge: "llm" | "deterministic";
            /** Model */
            model: string;
            /**
             * Org
             * @default toy
             */
            org: string;
            /**
             * Scaffold
             * @default baseline
             * @enum {string}
             */
            scaffold: "baseline" | "refusal_aware";
            /**
             * Seed
             * @default 0
             */
            seed: number;
        };
        /** RunStatus */
        RunStatus: {
            /** Error */
            error: string | null;
            report: components["schemas"]["Report"] | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
        };
        /** RunSummary */
        RunSummary: {
            /**
             * Archived
             * @default false
             */
            archived: boolean;
            /** Created At */
            created_at: string;
            /** Epochs */
            epochs: number;
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Grader */
            grader: string | null;
            /** Id */
            id: string;
            /** Judge */
            judge: string;
            /** Mean Rate */
            mean_rate: number | null;
            /** Model */
            model: string;
            /** Org */
            org: string;
            /** Pass K Rate */
            pass_k_rate: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
        };
        /** SiloField */
        SiloField: {
            /** Asserted At */
            asserted_at: string | null;
            /** Value */
            value: unknown;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Detail */
            detail: string | null;
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "offline" | "skipped";
        };
        /** StartRunResult */
        StartRunResult: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
        };
        /** TrendPoint */
        TrendPoint: {
            axes: components["schemas"]["ReportAxes"];
            /** Categories */
            categories: {
                [key: string]: number;
            };
            /** Created At */
            created_at: string;
            /** Engine */
            engine: string;
            /** Id */
            id: string;
            /** Mean Rate */
            mean_rate: number;
            /** Model */
            model: string;
            /** Org */
            org: string;
            /** Pass K Rate */
            pass_k_rate: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_blueprints_api_blueprints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintMeta"][];
                };
            };
        };
    };
    create_blueprint_api_blueprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_blueprint_api_blueprints_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_blueprint_api_blueprints_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprint_api_blueprints__blueprint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_blueprint_api_blueprints__blueprint_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blueprint_api_blueprints__blueprint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintDeleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_comparison_api_comparisons_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComparisonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    eval_setup_api_eval_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSetup"];
                };
            };
        };
    };
    list_evaluations_api_evaluations_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummary"][];
                };
            };
        };
    };
    import_evaluation_api_evaluations_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_evaluation_api_evaluations_import_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_diagnostics_api_evaluations__evaluation_id__diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostic"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluation_report_api_evaluations__evaluation_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                evaluation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_experiments_api_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"][];
                };
            };
        };
    };
    start_experiment_api_experiments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExperimentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_experiment_api_experiments__experiment_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Experiment"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    experiment_comparison_api_experiments__experiment_id__comparisons__variant_id__get: {
        parameters: {
            query?: {
                intervention?: ("model" | "org" | "engine" | "grader" | "k" | "scaffold" | "seed" | "harness") | null;
            };
            header?: never;
            path: {
                experiment_id: string;
                variant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentComparison"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resume_experiment_api_experiments__experiment_id__resume_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                experiment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExperimentStarted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leaderboard_api_leaderboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LeaderboardManifest"];
                };
            };
        };
    };
    list_logs_api_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogMeta"][];
                };
            };
        };
    };
    get_report_api_logs__log_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_api_model_discovery_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescanResult"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_orgs_api_orgs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    run_preflight_api_preflights_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PreflightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreflightResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    save_provider_api_providers__provider_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_report_api_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_report_api_reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                include_archived?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_run_api_runs__job_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ArchiveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_trends_get: {
        parameters: {
            query?: {
                org?: string | null;
                model?: string | null;
                engine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
