/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Orgs
         * @description Runnable orgs = built-in ORGS builders + saved blueprints from the store, so a
         *     dataset authored on the Datasets page is immediately runnable here. Raises (500)
         *     if a custom org module fails to import — surfaced by the frontend as a warning.
         */
        get: operations["list_orgs_api_orgs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Models
         * @description The published model set displayed by the Run form.
         */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/eval-setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Eval Setup
         * @description Return the typed, credential-safe vocabulary and defaults for the eval launcher.
         */
        get: operations["eval_setup_api_eval_setup_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Blueprints */
        get: operations["list_blueprints_api_blueprints_get"];
        put?: never;
        /** Create Blueprint */
        post: operations["create_blueprint_api_blueprints_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/{blueprint_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Blueprint */
        get: operations["get_blueprint_api_blueprints__blueprint_id__get"];
        /** Upsert Blueprint */
        put: operations["upsert_blueprint_api_blueprints__blueprint_id__put"];
        post?: never;
        /** Delete Blueprint */
        delete: operations["delete_blueprint_api_blueprints__blueprint_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate Blueprint */
        post: operations["validate_blueprint_api_blueprints_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/blueprints/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Blueprint
         * @description Compile in memory and return the resulting org (CRM db.json, docs, manifest) —
         *     no disk write, no eval. Powers the editor's live preview.
         */
        post: operations["preview_blueprint_api_blueprints_preview_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/logs/{log_id}/report": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Report */
        get: operations["get_report_api_logs__log_id__report_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/reports": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload Report */
        post: operations["upload_report_api_reports_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Runs
         * @description Run history (newest first) with headline rates — for the monitor + dashboard.
         */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        /** Start Run */
        post: operations["start_run_api_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run Events
         * @description Server-Sent Events stream of run status until terminal. SSE (not WebSocket) is
         *     simpler and more air-gap-friendly; the FE shows live status off this.
         */
        get: operations["run_events_api_runs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trends
         * @description Time-ordered series across finished runs (optionally filtered) for the dashboard:
         *     pass^k/mean overall, per-conflict pass^k, and the three axes.
         */
        get: operations["trends_api_trends_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Providers */
        get: operations["list_providers_api_providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/providers/{provider_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Provider */
        put: operations["save_provider_api_providers__provider_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/model-discovery/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan */
        post: operations["rescan_api_model_discovery_rescan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Artifacts */
        Artifacts: {
            /** Manifest */
            manifest: {
                [key: string]: components["schemas"]["ManifestEntry"];
            };
            /** Silos */
            silos: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: components["schemas"]["SiloField"];
                    };
                };
            };
            /** Docs */
            docs: components["schemas"]["DocFile"][];
        };
        /**
         * Blueprint
         * @description A fragmented organization: the claims it knows and the probes we ask it.
         */
        Blueprint: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Probes */
            probes?: components["schemas"]["Probe"][];
        };
        /** BlueprintDeleted */
        BlueprintDeleted: {
            /** Deleted */
            deleted: string;
        };
        /** BlueprintId */
        BlueprintId: {
            /** Id */
            id: string;
        };
        /** BlueprintMeta */
        BlueprintMeta: {
            /** Id */
            id: string;
            /** Claims */
            claims: number;
            /** Probes */
            probes: number;
        };
        /** Body_upload_report_api_reports_post */
        Body_upload_report_api_reports_post: {
            /** File */
            file: string;
        };
        /**
         * Claim
         * @description An atomic knowledge unit that lives in exactly one silo.
         */
        Claim: {
            /** Claim Id */
            claim_id: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Value */
            value: unknown;
            /** Silo */
            silo: string;
            /** Asserted At */
            asserted_at?: string | null;
            /** Authority */
            authority?: number | null;
            render: components["schemas"]["Render"];
        };
        /**
         * ConflictType
         * @description The four-way taxonomy at the heart of the eval: what kind of disagreement (if
         *     any) the silos hold for a probe. It decides whether the right move is to answer or
         *     to refuse, and `unresolvable` is the column that actually separates reliable agents
         *     from confident fabricators.
         * @enum {string}
         */
        ConflictType: "none" | "resolvable" | "unresolvable" | "void";
        /** DocFile */
        DocFile: {
            /** Path */
            path: string;
            /** Content */
            content: string;
        };
        /** EvalSetup */
        EvalSetup: {
            defaults: components["schemas"]["EvalSetupDefaults"];
            /** Models */
            models: components["schemas"]["EvalSetupModel"][];
            /** Suites */
            suites: components["schemas"]["EvalSetupSuite"][];
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
        };
        /** EvalSetupDefaults */
        EvalSetupDefaults: {
            /**
             * Engine
             * @constant
             */
            engine: "deterministic";
            /** Repeats */
            repeats: number;
            /** Grader */
            grader: string | null;
        };
        /** EvalSetupModel */
        EvalSetupModel: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Provider */
            provider: string;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "ready" | "needs_config" | "needs_server" | "offline" | "unverified";
            /** Source */
            source: string;
            /** Published */
            published: boolean;
            /** Released */
            released: string | null;
            /** Retired */
            retired: boolean;
            /** Detail */
            detail?: string | null;
        };
        /** EvalSetupSuite */
        EvalSetupSuite: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "builtin" | "custom";
            /** Editable */
            editable: boolean;
            /** Claims */
            claims: number;
            /** Questions */
            questions: number;
        };
        /**
         * ExpectedBehavior
         * @description What a correct agent does on this probe — the outcome the scorer grades against.
         * @enum {string}
         */
        ExpectedBehavior: "answer" | "refuse";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LogMeta */
        LogMeta: {
            /** Id */
            id: string;
            /** Source */
            source: string;
            /** Path */
            path: string;
            /** Model */
            model: string;
            /** Engine */
            engine: string;
            /** Grader */
            grader: string | null;
            /** Org */
            org: string | null;
            /** Created */
            created: string;
            /** K */
            k: number;
        };
        /** ManifestEntry */
        ManifestEntry: {
            /** Silo */
            silo: string;
            /** Subject */
            subject: string;
            /** Predicate */
            predicate: string;
            /** Artifact */
            artifact: string;
            /** Locator */
            locator: string;
        };
        /**
         * Probe
         * @description A question that references claims and declares expected behavior.
         */
        Probe: {
            /** Probe Id */
            probe_id: string;
            /** Question */
            question: string;
            /** References */
            references?: string[];
            conflict_type: components["schemas"]["ConflictType"];
            resolution_rule?: components["schemas"]["ResolutionRule"] | null;
            expected_behavior: components["schemas"]["ExpectedBehavior"];
            /** Expected Answer */
            expected_answer?: string | null;
            /** Expected Sources */
            expected_sources?: string[];
        };
        /** Provider */
        Provider: {
            /** Id */
            id: string;
            /** Configured */
            configured: boolean;
            /**
             * Readiness
             * @enum {string}
             */
            readiness: "configured" | "needs_config";
            /** Fields */
            fields: components["schemas"]["ProviderField"][];
        };
        /** ProviderField */
        ProviderField: {
            /** Id */
            id: string;
            /** Env Var */
            env_var: string;
            /** Configured */
            configured: boolean;
        };
        /** ProviderUpdate */
        ProviderUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
        };
        /**
         * Render
         * @description Rendering directive for a claim. ``as`` is aliased (Python keyword).
         */
        Render: {
            as: components["schemas"]["RenderAs"];
            /** Template */
            template?: string | null;
        };
        /**
         * RenderAs
         * @description How a claim is materialized into its silo.
         * @enum {string}
         */
        RenderAs: "field" | "prose";
        /** Report */
        Report: {
            header: components["schemas"]["ReportHeader"];
            overall: components["schemas"]["ReportOverall"];
            /** Categories */
            categories: components["schemas"]["ReportCategory"][];
            axes: components["schemas"]["ReportAxes"];
            /** Probes */
            probes: components["schemas"]["ReportProbe"][];
        };
        /** ReportAxes */
        ReportAxes: {
            /** Accuracy Rate */
            accuracy_rate: number | null;
            /** Provenance Rate */
            provenance_rate: number;
            /** Refusal Rate */
            refusal_rate: number | null;
            /** N Answer Epochs */
            n_answer_epochs: number;
            /** N Refuse Epochs */
            n_refuse_epochs: number;
            /** N Total Epochs */
            n_total_epochs: number;
            /** Answer Format Rate */
            answer_format_rate?: number | null;
        };
        /** ReportCategory */
        ReportCategory: {
            /** Key */
            key: string;
            /** N Probes */
            n_probes: number;
            /** Pass K Rate */
            pass_k_rate: number;
            /** Mean Rate */
            mean_rate: number;
            /** Flaky */
            flaky: boolean;
        };
        /** ReportFailure */
        ReportFailure: {
            /** Epoch */
            epoch: number;
            /** Passed */
            passed: boolean;
            /** Accuracy Ok */
            accuracy_ok: boolean;
            /** Provenance Ok */
            provenance_ok: boolean;
            /** Refusal Ok */
            refusal_ok: boolean;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Consulted */
            consulted: string[];
            /** Expected Sources */
            expected_sources: string[];
            /** Missing */
            missing: string[];
            /** Answer Format Ok */
            answer_format_ok?: boolean | null;
        };
        /** ReportHeader */
        ReportHeader: {
            /** Model */
            model: string;
            /** Engine */
            engine: string;
            /** Grader */
            grader: string | null;
            /** Org */
            org: string | null;
            /** K */
            k: number;
            /** Created */
            created: string;
            /** Location */
            location: string;
            /** Scorer Version */
            scorer_version?: string | null;
            /** Inspect Ai Version */
            inspect_ai_version?: string | null;
            /** Scaffold */
            scaffold?: string | null;
            /** Seed */
            seed?: number | null;
            /** Harness */
            harness?: string | null;
        };
        /** ReportOverall */
        ReportOverall: {
            /** Pass K Rate */
            pass_k_rate: number;
            /** Mean Rate */
            mean_rate: number;
        };
        /** ReportProbe */
        ReportProbe: {
            /** Probe Id */
            probe_id: string;
            /** Conflict Type */
            conflict_type: string;
            /** Expected Behavior */
            expected_behavior: string;
            /** Epochs Total */
            epochs_total: number;
            /** Epochs Passed */
            epochs_passed: number;
            /** Pass K */
            pass_k: boolean;
            /** Mean Pass */
            mean_pass: number;
            /** Failures */
            failures: components["schemas"]["ReportFailure"][];
        };
        /** RescanResult */
        RescanResult: {
            /** Sources */
            sources: components["schemas"]["SourceStatus"][];
            /** Model Count */
            model_count: number;
        };
        /**
         * ResolutionRule
         * @description How a `resolvable` conflict is decided. Note authority can outrank recency: a
         *     source that declares itself binding wins even over a fresher one.
         * @enum {string}
         */
        ResolutionRule: "recency_wins" | "authority_wins";
        /** RunRequest */
        RunRequest: {
            /** Model */
            model: string;
            /** Grader */
            grader?: string | null;
            /**
             * Judge
             * @default llm
             * @enum {string}
             */
            judge: "llm" | "deterministic";
            /**
             * Org
             * @default toy
             */
            org: string;
            /**
             * Epochs
             * @default 3
             */
            epochs: number;
        };
        /** RunStatus */
        RunStatus: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            report: components["schemas"]["Report"] | null;
            /** Error */
            error: string | null;
        };
        /** RunSummary */
        RunSummary: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
            /** Error */
            error: string | null;
            /** Model */
            model: string;
            /** Org */
            org: string;
            /** Judge */
            judge: string;
            /** Grader */
            grader: string | null;
            /** Epochs */
            epochs: number;
            /** Created At */
            created_at: string;
            /** Finished At */
            finished_at: string | null;
            /** Pass K Rate */
            pass_k_rate: number | null;
            /** Mean Rate */
            mean_rate: number | null;
        };
        /** SiloField */
        SiloField: {
            /** Value */
            value: unknown;
            /** Asserted At */
            asserted_at: string | null;
        };
        /** SourceStatus */
        SourceStatus: {
            /** Source */
            source: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "offline" | "skipped";
            /** Detail */
            detail: string | null;
        };
        /** StartRunResult */
        StartRunResult: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "done" | "error";
        };
        /** TrendPoint */
        TrendPoint: {
            /** Id */
            id: string;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
            /** Org */
            org: string;
            /** Engine */
            engine: string;
            /** Pass K Rate */
            pass_k_rate: number;
            /** Mean Rate */
            mean_rate: number;
            /** Categories */
            categories: {
                [key: string]: number;
            };
            axes: components["schemas"]["ReportAxes"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** ValidationIssue */
        ValidationIssue: {
            /** Location */
            location: string;
            /** Message */
            message: string;
        };
        /** ValidationResult */
        ValidationResult: {
            /** Ok */
            ok: boolean;
            /** Errors */
            errors: components["schemas"]["ValidationIssue"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_orgs_api_orgs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    eval_setup_api_eval_setup_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvalSetup"];
                };
            };
        };
    };
    list_blueprints_api_blueprints_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintMeta"][];
                };
            };
        };
    };
    create_blueprint_api_blueprints_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_blueprint_api_blueprints__blueprint_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Blueprint"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_blueprint_api_blueprints__blueprint_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintId"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_blueprint_api_blueprints__blueprint_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                blueprint_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BlueprintDeleted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_blueprint_api_blueprints_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_blueprint_api_blueprints_preview_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artifacts"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_logs_api_logs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogMeta"][];
                };
            };
        };
    };
    get_report_api_logs__log_id__report_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                log_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_report_api_reports_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_report_api_reports_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Report"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunSummary"][];
                };
            };
        };
    };
    start_run_api_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartRunResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_events_api_runs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trends_api_trends_get: {
        parameters: {
            query?: {
                org?: string | null;
                model?: string | null;
                engine?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_providers_api_providers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    save_provider_api_providers__provider_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                provider_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProviderUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rescan_api_model_discovery_rescan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescanResult"];
                };
            };
        };
    };
}
